In [1]:
import pandas as pd
import numpy as np
from load_data import load_data

In [2]:
recipes, ingredients, favorites, comments, users, chat_history = load_data()

FileNotFoundError: [Errno 2] No such file or directory: 'E:\\data-science\\data\\seed\\recipes.csv'

EDA

In [ ]:
print("Recipes:", recipes.shape)
print("Ingredients:", ingredients.shape)
print("Favorites:", favorites.shape)
print("Comments:", comments.shape)
print("Users:", users.shape)
print("Chat History:", chat_history.shape)

Recipes: (2000, 13)
Ingredients: (11223, 8)
Favorites: (6000, 3)
Comments: (4000, 7)
Users: (200, 6)
Chat History: (2000, 6)

In [ ]:
recipes.head()

,id,user_id,name,caption,category,estimated_time,calories,fats,carbs,protein,likes,created_at,updated_at
0,1,105,Simple Beef Tomato Pasta,A healthy breakfast recipe.,breakfast,79,657,16.30,28.62,24.85,463,2026-01-28 12:00:00,2026-07-16 12:00:00
1,2,193,Healthy Chicken Garlic Pasta,A homemade lunch recipe.,lunch,63,731,26.92,59.15,34.37,112,2026-08-08 12:00:00,2026-05-14 12:00:00
2,3,87,Simple Egg and Cheese Breakfast,A homemade breakfast recipe.,breakfast,31,658,32.43,98.26,30.77,464,2026-07-19 12:00:00,2026-01-03 12:00:00
3,4,35,Simple Lentil Vegetable Bowl,A homemade vegan recipe.,vegan,33,231,11.33,39.46,26.64,172,2026-07-09 12:00:00,2026-07-09 12:00:00
4,5,5,Creamy Beef Rice Bowl,A flavorful breakfast recipe.,breakfast,16,538,10.18,16.18,52.78,20,2026-01-08 12:00:00,2026-04-27 12:00:00

In [ ]:
recipes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              2000 non-null   int64
 1   user_id         2000 non-null   int64
 2   name            2000 non-null   object
 3   caption         2000 non-null   object
 4   category        2000 non-null   object
 5   estimated_time  2000 non-null   int64
 6   calories        2000 non-null   int64
 7   fats            2000 non-null   float64
 8   carbs           2000 non-null   float64
 9   protein         2000 non-null   float64
 10  likes           2000 non-null   int64
 11  created_at      2000 non-null   object
 12  updated_at      2000 non-null   object
dtypes: float64(3), int64(5), object(5)
memory usage: 203.3+ KB

In [ ]:
recipes.describe()

,id,user_id,estimated_time,calories,fats,carbs,protein,likes
count,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000
mean,1000.500000,99.469500,49.685500,509.720500,18.665135,56.543895,28.883565,246.781500
std,577.494589,58.041575,23.249793,196.865463,9.213728,25.987246,14.968665,143.478482
min,1.000000,1.000000,10.000000,180.000000,3.010000,10.020000,3.030000,0.000000
25%,500.750000,49.000000,29.000000,333.000000,10.540000,34.587500,16.190000,120.000000
50%,1000.500000,99.000000,49.000000,501.000000,18.245000,56.805000,28.900000,244.500000
75%,1500.250000,150.000000,70.000000,682.250000,26.752500,79.757500,41.765000,372.000000
max,2000.000000,200.000000,90.000000,850.000000,35.000000,99.980000,54.970000,500.000000

In [ ]:
recipes.duplicated().sum()

np.int64(0)

In [ ]:
recipes["category"].value_counts()

category
lunch        484
breakfast    480
dinner       469
vegan        298
dessert      269
Name: count, dtype: int64

In [ ]:
favorites.head()

   user_id  recipe_id           created_at
0      193       1261  2026-05-18 14:00:00
1      167         18  2026-08-27 14:00:00
2       35       1600  2026-01-27 14:00:00
3      113       1566  2026-05-24 14:00:00
4       89       1365  2026-05-11 14:00:00

In [ ]:
favorites.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6000 entries, 0 to 5999
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   user_id     6000 non-null   int64
 1   recipe_id   6000 non-null   int64
 2   created_at  6000 non-null   object
dtypes: int64(2), object(1)
memory usage: 140.8+ KB

In [ ]:
favorites.duplicated().sum()

np.int64(0)

In [ ]:
ingredients.head()

,id,recipe_id,name,quantity,unit,is_assigned,created_at,updated_at
0,1,1,onion,4.12,piece,False,2026-01-28 12:00:00,2026-07-16 12:00:00
1,2,1,bell pepper,1.21,kg,False,2026-01-28 12:00:00,2026-07-16 12:00:00
2,3,1,olive oil,4.00,ml,False,2026-01-28 12:00:00,2026-07-16 12:00:00
3,4,1,salt,1.22,piece,False,2026-01-28 12:00:00,2026-07-16 12:00:00
4,5,1,garlic,2.44,cup,False,2026-01-28 12:00:00,2026-07-16 12:00:00

In [ ]:
ingredients.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11223 entries, 0 to 11222
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           11223 non-null  int64
 1   recipe_id    11223 non-null  int64
 2   name         11223 non-null  object
 3   quantity     11223 non-null  float64
 4   unit         11223 non-null  object
 5   is_assigned  11223 non-null  bool
 6   created_at   11223 non-null  object
 7   updated_at   11223 non-null  object
dtypes: bool(1), float64(1), int64(2), object(4)
memory usage: 624.8+ KB

In [ ]:
ingredients.duplicated().sum()

np.int64(0)

In [ ]:
ingredients["name"].value_counts()

name
olive oil         1134
garlic            1122
black pepper       961
salt               953
onion              926
butter             625
tomato             561
milk               449
eggs               428
lemon              386
flour              219
cheese             212
cocoa powder       209
sugar              207
vanilla            205
cumin              202
chicken breast     198
bell pepper        197
chickpeas          195
basil              192
parmesan           191
zucchini           191
pasta              188
lentils            185
rice               184
beef               176
chicken thighs     176
potato             176
carrot             175
Name: count, dtype: int64

In [ ]:
favorites_per_user = favorites.groupby("user_id").size()

In [ ]:
favorites_per_user.describe()

count    200.00000
mean      30.00000
std        5.47539
min       17.00000
25%       26.00000
50%       30.00000
75%       34.00000
max       43.00000
dtype: float64